### ISSUE TITLE
UI iPad adjustments

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#137]
**Suggested adjustments to iPad-version of BTV app 4.0:**

- [x]  Feature banner in scroll: Adjust height that will result in porpotion closer to 16:9
- [x]  Hero/feature banner on top: Adjust height that will result in porpotion closer to 16:9. If it takes to much space we can consider having close to two banners on top..
- [ ] Scrollable player after play
- [x]  Change small thumbs and small posters to be shown as medium if tablet.
- [x]  Adjust size of category buttons a bit larger, same as web (I have a design of that in Figma)
- [x]  On video player page, consider changing the size of thumbnails to the same size as medium thumb?

**Comment by andreasgangso** [comment]
Only missing iOS scrollable player now. That and any future ipad adjustments will get a new issue.

This issue is closed by these PRs by @eliezerben:
https://github.com/bcc-code/bcc-media-app/pull/165
https://github.com/bcc-code/bcc-media-app/pull/166
https://github.com/bcc-code/bcc-media-app/pull/176
https://github.com/bcc-code/bcc-media-app/pull/178
https://github.com/bcc-code/bcc-media-app/pull/177
https://github.com/bcc-code/bcc-media-app/pull/179
https://github.com/bcc-code/bcc-media-app/pull/180
