### ISSUE TITLE
Identify issues with publishing bccm_player

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-app#215]
Using the bccm_player/example/ flutter project, try setting up a project from scratch.

Write a report as a comment on this issue containing:
- Anything lacking/confusing with the documentation.
- Anything hard to implement, e.g. because it's too tightly-coupled to our app.
- Other issues that could be a blocker for people to adopt the plugin compared to alternatives.

Follow the bccm_player README.md to set things up.
Set up a project that:

- Uses flutter controls: `useNativeControls: false`, because this will likely be the default later.
- Plays some HLS videos: https://gist.github.com/Fazzani/8f89546e188f8086a46073dc5d4e2928 (we are lacking normal video support and dash at the moment...)
- Can go pip
- Can go fullscreen
- Can play videos in the background (and shows up in notification center with basic play/pause control)
- Can cast to a chromecast.

**Comment by eliezerben** [comment]
**Anything lacking/confusing with the documentation:**
- After initialization, I found it a bit difficult to figure out how to create a player and play a video just from reading the docs. Would have been easier if the example showed how to play a video. i.e by calling `replaceCurrentMediaItem`.
- Certain steps are not mentioned in the docs. For example, to use PIP mode, "android:supportsPictureInPicture" should be set in AndroidManifest.xml. 
- For Cast option
    - Requires changing `FlutterActivity` to `FlutterFragmentActivity` which is not mentioned in the docs.
    - Requires setting `mediaRouteTheme` in styles.xml which is not mentioned in the docs.

**Anything hard to implement / Other issues that could be a blocker for people to adopt the plugin compared to alternatives.**
- The alternatives seem to follow a more idiomatic approach. So they may be easier to use for simple use cases. i.e Create a controller with player details and pass it to a Player widget. No need for initialization in main() / watching the primaryPlayerProvider, etc.
- Some of the alternatives have the ability to create more than one player on the same page. Not sure if that is supported in BccmPlayer.

**Bugs / Other points I noticed**
- If an invalid url is given, a blank video is played continuously. There is no indication that there was an error. In this state, the play/pause button is unresponsive. Trying to seek, changes the current time of the video to some random large number.
- Not sure if the player provides a way to catch errors so that some message can be shown.
- When there are no additional tracks, clicking on settings button of the player shows blank overlay.
- Casting didn't work for this video 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8'. Worked for two others I tried.
- When I pause the video first and then cast, the video doesn't get casted. The controls in the cast view are disabled and clicking on the cast button in the cast view shows 'No media selected'. However I don't see this issue on the Bcc Media app.
- After casting is stopped, not able to continue watching on the phone. The player controls go into an unresponsive state.

**Comment by andreasgangso** [comment]
@eliezerben do you still happen to have the code you wrote for this somewhere?
