### ISSUE TITLE
Flutter player: UI adjustment

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#237]
- [ ] Player setting Font: Barlow Medium 16
- [x] Add 15s into rewind/ skip button

![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/c6301e0a-11b7-46ab-8b16-f8bc82c3fe03)

**Comment by andreasgangso** [comment]
Do you mean to add the text "15s", or to actually skip 15 seconds more?

By the way, the skip/rewind buttons are dynamic:
default: 15 seconds
if duration > 1 hour: 30 seconds

**Comment by mulundapm** [comment]
Add the text "15s"

**Comment by andreasgangso** [comment]
I think **body2** (which is barlow medium 16) looks a bit big and unnatural

![Image](https://github.com/bcc-code/bcc-media-app/assets/727125/5722e33a-8917-4c72-a9cf-f2913fe09c2d)


For a quick fix, I'd suggest **caption1** (similar to the original but it's actually a part of our typography system)
![Image](https://github.com/bcc-code/bcc-media-app/assets/727125/7a2f2b84-329d-409a-a00e-0af828dc4e2a)


The problem here is more that this component is a bit out-of-style. Probably should be more similar to the season and link-sharing bottom sheets. I don't think it's worth our time to struggle with the player ui much as long as it's usable and not awful. 

At some point søren is going to need to bring the player ui into figma, e.g. when we make chapters so I expect he'll make some changes

**Comment by andreasgangso** [comment]
I changed to caption1 for now
