### ISSUE TITLE
Chromecast 3. disconnects every 15min

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#276]
Chromecast dies every 15 minutes. I need to stop casting, recast, to fix it.
3 gen. 

![Image](https://github.com/bcc-code/bcc-media-app/assets/88234679/20d37c13-102d-4320-98f1-b3906f2a35bb)

I've never seen the issue before today (07. okt). I'm watching live. 
For the first 45 minutes I had to reconnect 3-4 times. 
it disconnects and have to be recasted while the Chromecast is still on
It cuts from video to the BCC Media screen. 
I then had to....
"Stop casting"...."start casting""

https://projects.bcc.no/desk/tickets/10533130/messages

**Comment by andreasgangso** [comment]
how did this go @ høstcamp?

**Comment by mulundapm** [comment]
checking with user

**Comment by mulundapm** [comment]
The same user didnt have this issue during høstcamp

**Comment by andreasgangso** [comment]
Couldnt find any cpu/memory issue in the receiver js.

Its probably an overheating issue if theyve had their chromecast running for a long time or something.
I tried with a cooled down chromecast now and its been running for 1.5hours.

for the record ive been testing this on an ultra because it was reproducable there too and couldnt find our 3rd gen

**Comment by andreasgangso** [comment]
The only workaround I can see is to cap the quality to 720p or lower, but that would be unfortunate for those its working for.
I think for now we should just track how many support tickets are coming in and tell them "it might be overheated", and ask them to "try again after letting it cool and let us know if that helped.".

If many, we can try harder to resolve this.
