### ISSUE TITLE
U36 frontpage doesnt show on launch

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#383]
2 issues

1. When launch app for the first time within a day, have to refresh homepage in order to fetch the U36 homepage

2. When updating from 5.4.7 to 5.4.9 for the first time, after logging in, the U36 frontpage doesnt show. Refresh several times doesnt help, had to force quit for the U36 front page to show on next launch. 

Reproducible on both iOS and Android

**Comment by andreasgangso** [comment]
Technical notes.
I've identified what the issue is.

Currently the order is like this ish (maybe some parallel):

1. App launch: unleash is initialized with cached data (initialize event)
2. Unleash `update` event: fetched new toggles with empty context (since auth isnt loaded), **now we lost the cached feature flags in favor of the "updated" feature flags**
3. We load auth, which could take multiple seconds if it's doing a refresh
4. Auth is done: we load the home page
5. At some point we refresh unleash

Also noticed a few too many getHomePage() requests.

Action points:
- Simplify home.dart listening of appconfig. Only fetch when page code changes
- Keep the cached feature flags until auth is done.
- Make sure unleash refreshes on auth states.

**Comment by mulundapm** [comment]
Case 2 is still happening. Testing with 5.5.1 on ios, the u36 front page is not shown on first launch after updating. Had to force quit

https://github.com/bcc-code/bcc-media-app/assets/88234679/6360560d-081c-4b69-a1e0-3112b8254826
