### ISSUE TITLE
apps not receiving notification

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-app#467]
3 notification were scheduled to be sent 4.-6. okt. Users didnt receive the notification

3 users with 0.4.7 seems to receive the notification (an app version that was replaced on 4. sept by 0.4.12)
https://metabase.bcc.media/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjQwNDd9fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319

**Comment by KillerX** [comment]
I sent a notification today at 9:40 to 
<img width="761" alt="image" src="https://github.com/user-attachments/assets/ca321098-ef5c-4ee9-be7c-bbd3ce10b5e1">

Pending feedback if the notification arrived. It did arrive on my phone, need to confirm if that is an exception or if the fix of upgrading the libs worked.

The reason earlier tests did not work at all was because the triggering and updating are in the same flow and one or the other happens. By manually triggering it I actually just made it update something. Possibly something we want to improve in the future, but it's a bit risky and I don't want to spend lots of time on refactoring for a minor improvement in rare debug scenarios.

**Comment by sifferhans** [comment]
I did not receive a notification

**Comment by KillerX** [comment]
As far as I can tell it works now. @mulundapm please do another test just to be sure that I didn't do stuff in a different way that "made it work". Thanks.
